# Generated by Django 5.0.6 on 2024-07-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
