# Generated by Django 5.0.6 on 2024-06-10 17:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_initial'),
        ('pins', '0002_rename_author_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='tags',
            field=models.ManyToManyField(related_name='pins', to='pins.tag'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins_set', to='boards.board'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
