# Generated by Django 5.0.7 on 2024-07-25 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('pins', '0002_alter_pin_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pins_set', to='boards.board'),
        ),
    ]
