# Generated by Django 5.0.7 on 2024-08-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_alter_pin_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ['-date_created']},
        ),
    ]
