# Generated by Django 5.0.6 on 2024-06-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_generatedimage_pin_generated_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='file',
            field=models.FileField(null=True, upload_to='pins'),
        ),
    ]
