# Generated by Django 5.0.6 on 2024-06-16 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0006_remove_comment_parent_commentreplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreplies',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pins.commentreplies'),
        ),
        migrations.AlterField(
            model_name='commentreplies',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commentreplies',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
