# Generated by Django 5.0.6 on 2024-06-17 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0007_commentreplies_parent_reply_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_pins', to=settings.AUTH_USER_MODEL),
        ),
    ]
