# Generated by Django 5.0.6 on 2024-06-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0009_likepins_savepins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='file',
        ),
        migrations.AddField(
            model_name='pin',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pins/images'),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='pins/videos'),
        ),
    ]
