# Generated by Django 5.0.6 on 2024-06-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0011_rename_pin_image_url_pin_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='video_url',
        ),
    ]
