# Generated by Django 5.0.6 on 2024-06-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0012_remove_pin_image_url_remove_pin_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='pin',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
