# Generated by Django 5.0.6 on 2024-06-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0013_remove_pin_tags_delete_tag_pin_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='video',
        ),
        migrations.AddField(
            model_name='pin',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pins/files'),
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
