# Generated by Django 5.0.6 on 2024-06-29 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0014_remove_pin_image_remove_pin_video_pin_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='tags',
        ),
    ]
