# Generated by Django 5.0.6 on 2024-06-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0015_remove_pin_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='generated_image',
        ),
        migrations.AlterField(
            model_name='pin',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='GeneratedImage',
        ),
    ]
