# Generated by Django 5.0.6 on 2024-06-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0016_remove_pin_generated_image_alter_pin_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='file',
        ),
        migrations.AddField(
            model_name='pin',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pins/images'),
        ),
        migrations.AddField(
            model_name='pin',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='pins/videos'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
