# Generated by Django 5.0.6 on 2024-06-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0017_remove_pin_file_pin_image_pin_video_alter_pin_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.FileField(default='default/image.jpg', upload_to='pins/images'),
        ),
    ]
