# Generated by Django 5.0.6 on 2024-06-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_board_pins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cover',
            field=models.ImageField(default='boards/default.png', null=True, upload_to='boards'),
        ),
    ]
